[package]
name = "generic_traits_lifetimes"
version = "0.1.0"
authors = ["Xunjin <xunjin.coder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
